### ISSUE TITLE
Build fails for davinci when using newer / latest clang

### ISSUE THREAD

**Issue by helliscloser** [crdroidandroid/android_kernel_xiaomi_sm6150#4]
Currently, I'm building with the default clang that is 17.0.2. 
It works with 17.0.4 too, but not with latest clang or any clang 18.

If you have some time to spare, please take a look.

https://paste.crdroid.net/VjudtW

Here's my fork just for reference.
https://github.com/sm6150-davinci/cr_kernel_xiaomi_sm6150

Thank you.

**Comment by neobuddy89** [comment]
Fix errors yourself

../../../../../../kernel/xiaomi/sm6150/drivers/input/touchscreen/goodix_driver_gt9886/goodix_ts_core.c:2527:3: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
 2527 |                 if (core_data->gtp_tp_class == NULL)
      |                 ^
../../../../../../kernel/xiaomi/sm6150/drivers/input/touchscreen/goodix_driver_gt9886/goodix_ts_core.c:2524:2: note: previous statement is here
 2524 |         if (core_data->gtp_tp_class == NULL)
      |         ^
1 error generated.
